import os
import sqlite3
from datetime import datetime, timedelta, timezone
from pathlib import Path

import jwt
from pwdlib import PasswordHash

try:
    import psycopg
except ImportError:
    psycopg = None


BASE_DIR = Path(__file__).resolve().parent

# ---------------------------------------------------------
# Database configuration
# ---------------------------------------------------------
#
# Local development:
#   No DATABASE_URL -> SQLite
#
# Render deployment:
#   DATABASE_URL -> PostgreSQL
#

DATABASE_URL = os.getenv("DATABASE_URL")

SQLITE_DATABASE_PATH = Path(
    os.getenv(
        "DATABASE_PATH",
        str(BASE_DIR / "caseassist.db"),
    )
)


def get_connection():
    """
    Use PostgreSQL when DATABASE_URL exists.
    Otherwise use local SQLite.
    """

    if DATABASE_URL:
        if psycopg is None:
            raise RuntimeError(
                "PostgreSQL driver is not installed. "
                "Run: pip install psycopg[binary]"
            )

        return psycopg.connect(DATABASE_URL)

    connection = sqlite3.connect(
        SQLITE_DATABASE_PATH
    )
    connection.row_factory = sqlite3.Row

    return connection


# ---------------------------------------------------------
# JWT configuration
# ---------------------------------------------------------

JWT_SECRET_KEY = os.getenv(
    "JWT_SECRET_KEY",
    "CHANGE_THIS_SECRET_KEY_IN_PRODUCTION",
)

JWT_ALGORITHM = "HS256"

JWT_EXPIRE_MINUTES = int(
    os.getenv(
        "JWT_EXPIRE_MINUTES",
        "1440",
    )
)


# ---------------------------------------------------------
# Password hashing
# ---------------------------------------------------------

password_hash = PasswordHash.recommended()


# ---------------------------------------------------------
# Database initialization
# ---------------------------------------------------------

def init_database():
    connection = get_connection()

    try:
        if DATABASE_URL:
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL,
                    email TEXT NOT NULL UNIQUE,
                    password_hash TEXT NOT NULL,
                    created_at TEXT NOT NULL
                )
                """
            )
        else:
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    name TEXT NOT NULL,
                    email TEXT NOT NULL UNIQUE,
                    password_hash TEXT NOT NULL,
                    created_at TEXT NOT NULL
                )
                """
            )

        connection.commit()

    finally:
        connection.close()


# ---------------------------------------------------------
# Create user
# ---------------------------------------------------------

def create_user(
    name: str,
    email: str,
    password: str,
):
    normalized_email = email.strip().lower()

    connection = get_connection()

    try:
        existing_user = connection.execute(
            """
            SELECT id
            FROM users
            WHERE email = %s
            """
            if DATABASE_URL
            else
            """
            SELECT id
            FROM users
            WHERE email = ?
            """,
            (normalized_email,),
        ).fetchone()

        if existing_user:
            return None

        hashed_password = password_hash.hash(password)

        created_at = datetime.now(
            timezone.utc
        ).isoformat()

        if DATABASE_URL:
            cursor = connection.execute(
                """
                INSERT INTO users (
                    name,
                    email,
                    password_hash,
                    created_at
                )
                VALUES (%s, %s, %s, %s)
                RETURNING id
                """,
                (
                    name.strip(),
                    normalized_email,
                    hashed_password,
                    created_at,
                ),
            )

            user_id = cursor.fetchone()[0]

        else:
            cursor = connection.execute(
                """
                INSERT INTO users (
                    name,
                    email,
                    password_hash,
                    created_at
                )
                VALUES (?, ?, ?, ?)
                """,
                (
                    name.strip(),
                    normalized_email,
                    hashed_password,
                    created_at,
                ),
            )

            user_id = cursor.lastrowid

        connection.commit()

        return {
            "id": user_id,
            "name": name.strip(),
            "email": normalized_email,
            "createdAt": created_at,
        }

    finally:
        connection.close()


# ---------------------------------------------------------
# Find user
# ---------------------------------------------------------

def get_user_by_email(email: str):
    normalized_email = email.strip().lower()

    connection = get_connection()

    try:
        user = connection.execute(
            """
            SELECT
                id,
                name,
                email,
                password_hash,
                created_at
            FROM users
            WHERE email = %s
            """
            if DATABASE_URL
            else
            """
            SELECT
                id,
                name,
                email,
                password_hash,
                created_at
            FROM users
            WHERE email = ?
            """,
            (normalized_email,),
        ).fetchone()

        if not user:
            return None

        if DATABASE_URL:
            return {
                "id": user[0],
                "name": user[1],
                "email": user[2],
                "password_hash": user[3],
                "created_at": user[4],
            }

        return dict(user)

    finally:
        connection.close()


# ---------------------------------------------------------
# Password verification
# ---------------------------------------------------------

def verify_password(
    password: str,
    hashed_password: str,
):
    try:
        return password_hash.verify(
            password,
            hashed_password,
        )
    except Exception:
        return False


# ---------------------------------------------------------
# JWT creation
# ---------------------------------------------------------

def create_access_token(
    user_id: int,
    email: str,
):
    expires_at = (
        datetime.now(timezone.utc)
        + timedelta(
            minutes=JWT_EXPIRE_MINUTES
        )
    )

    payload = {
        "sub": str(user_id),
        "email": email,
        "exp": expires_at,
    }

    token = jwt.encode(
        payload,
        JWT_SECRET_KEY,
        algorithm=JWT_ALGORITHM,
    )

    return token


# ---------------------------------------------------------
# JWT decoding
# ---------------------------------------------------------

def decode_access_token(token: str):
    try:
        payload = jwt.decode(
            token,
            JWT_SECRET_KEY,
            algorithms=[JWT_ALGORITHM],
        )

        return payload

    except jwt.ExpiredSignatureError:
        return None

    except jwt.InvalidTokenError:
        return None
