import { Info, RefreshCw, Sparkles } from 'lucide-react';
import { cn } from '@/utils/cn';

/** Split text into paragraphs and "- " bullet lists. Only ever produces React elements (no HTML injection). */
function parseBlocks(text) {
  const blocks = [];
  let list = null;
  for (const line of String(text).split('\n')) {
    const bullet = line.match(/^\s*[-\u2022]\s+(.*)$/);
    if (bullet) {
      if (!list) {
        list = { type: 'list', items: [] };
        blocks.push(list);
      }
      list.items.push(bullet[1]);
      continue;
    }
    list = null;
    if (line.trim()) blocks.push({ type: 'p', text: line.trim() });
  }
  return blocks;
}

function Inline({ text }) {
  return String(text)
    .split(/(\*\*[^*]+\*\*)/g)
    .map((part, i) =>
      part.startsWith('**') && part.endsWith('**') && part.length > 4 ? (
        <strong key={i} className="font-semibold">
          {part.slice(2, -2)}
        </strong>
      ) : (
        <span key={i}>{part}</span>
      ),
    );
}

function Content({ text }) {
  return (
    <div className="space-y-2.5">
      {parseBlocks(text).map((block, i) =>
        block.type === 'list' ? (
          <ul key={i} className="space-y-1.5">
            {block.items.map((item, j) => (
              <li key={j} className="flex gap-2.5">
                <span className="mt-2 size-1.5 shrink-0 rounded-full bg-verdigris-500 dark:bg-verdigris-300" aria-hidden="true" />
                <span>
                  <Inline text={item} />
                </span>
              </li>
            ))}
          </ul>
        ) : (
          <p key={i}>
            <Inline text={block.text} />
          </p>
        ),
      )}
    </div>
  );
}

export default function ChatMessage({ message, onRetry }) {
  if (message.role === 'system') {
    return (
      <div className="flex items-center gap-3 py-1 text-xs text-ink-500 dark:text-ink-400">
        <span className="h-px flex-1 bg-ink-200/80 dark:bg-white/10" />
        <span>{message.content}</span>
        <span className="h-px flex-1 bg-ink-200/80 dark:bg-white/10" />
      </div>
    );
  }

  if (message.role === 'user') {
    return (
      <div className="flex justify-end">
        <div className="max-w-[85%] rounded-2xl rounded-br-md bg-verdigris-600 px-4 py-2.5 text-sm leading-relaxed text-white dark:bg-verdigris-400/90 dark:text-ink-950">
          {message.content}
        </div>
      </div>
    );
  }

  return (
    <div className="flex items-start gap-2.5">
      <span
        className="mt-0.5 grid size-7 shrink-0 place-items-center rounded-lg bg-gradient-to-br from-verdigris-400 to-verdigris-700 text-white"
        aria-hidden="true"
      >
        <Sparkles className="size-3.5" />
      </span>

      <div className="min-w-0 max-w-[88%]">
        <div
          className={cn(
            'rounded-2xl rounded-tl-md border px-4 py-3 text-sm leading-relaxed',
            message.error
              ? 'border-rose-500/30 bg-rose-500/10 text-rose-800 dark:text-rose-200'
              : 'border-ink-200/70 bg-white/65 text-ink-800 dark:border-white/10 dark:bg-white/[0.06] dark:text-ink-100',
          )}
        >
          <Content text={message.content} />
          {message.error && onRetry && (
            <button
              type="button"
              onClick={onRetry}
              className="mt-3 inline-flex items-center gap-1.5 text-xs font-medium underline-offset-2 hover:underline"
            >
              <RefreshCw className="size-3.5" aria-hidden="true" />
              Try again
            </button>
          )}
        </div>

        {message.source === 'demo' && (
          <p className="mt-1.5 flex items-center gap-1.5 pl-1 text-[11px] text-ink-500 dark:text-ink-400">
            <Info className="size-3 shrink-0" aria-hidden="true" />
            Demo response built from your analysis. Not generated by an AI model.
          </p>
        )}
      </div>
    </div>
  );
}
